version: '3'
services:
  api:
    build: .
    environment:
      JWT_TOKEN: ${JWT_TOKEN}
      MONGO_USER: ${MONGO_USER}
      MONGO_PASSWORD: ${MONGO_PASSWORD}
    command: npm run start:dev
    volumes:
      - .:/app/
      - /app/node_modules
    ports:
      - "8000:8000"
    extra_hosts:
      - db1:127.0.0.1
